// <auto-generated />
namespace SinExWebApp20328800.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class hehe_5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hehe_5));
        
        string IMigrationMetadata.Id
        {
            get { return "201704091205249_hehe_5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
